### ISSUE TITLE
enum.utils.Color renamed to enum.utils.Colour

### ISSUE THREAD

**Issue by mngan** [peering-manager/docker#22]
In PM1.7 it looks like the name of `enum.utils.Color` was changed to `enum.utils.Colour`. So the startup script in the docker image needs to be similarly updated to match 

```
peering-manager_1         | Traceback (most recent call last):
peering-manager_1         |   File "/opt/peering-manager/./manage.py", line 11, in <module>
peering-manager_1         |     execute_from_command_line(sys.argv)
peering-manager_1         |   File "/opt/peering-manager/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
peering-manager_1         |     utility.execute()
peering-manager_1         |   File "/opt/peering-manager/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
peering-manager_1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
peering-manager_1         |   File "/opt/peering-manager/venv/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
peering-manager_1         |     self.execute(*args, **cmd_options)
peering-manager_1         |   File "/opt/peering-manager/venv/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
peering-manager_1         |     output = self.handle(*args, **options)
peering-manager_1         |   File "/opt/peering-manager/venv/lib/python3.9/site-packages/django/core/management/commands/shell.py", line 127, in handle
peering-manager_1         |     exec(sys.stdin.read(), globals())
peering-manager_1         |   File "<string>", line 1, in <module>
peering-manager_1         |   File "/usr/lib/python3.9/runpy.py", line 285, in run_path
peering-manager_1         |     return _run_code(code, mod_globals, init_globals,
peering-manager_1         |   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
peering-manager_1         |     exec(code, run_globals)
peering-manager_1         |   File "/opt/peering-manager/startup_scripts/__main__.py", line 21, in <module>
peering-manager_1         |     runpy.run_path(f.path)
peering-manager_1         |   File "/usr/lib/python3.9/runpy.py", line 268, in run_path
peering-manager_1         |     return _run_module_code(code, init_globals, run_name,
peering-manager_1         |   File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
peering-manager_1         |     _run_code(code, mod_globals, init_globals,
peering-manager_1         |   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
peering-manager_1         |     exec(code, run_globals)
peering-manager_1         |   File "/opt/peering-manager/startup_scripts/020_tags.py", line 3, in <module>
peering-manager_1         |     from utils.enums import Color
peering-manager_1         | ImportError: cannot import name 'Color' from 'utils.enums' (/opt/peering-manager/utils/enums.py)
peering-manager-docker_peering-manager_1 exited with code 1
```

**Comment by mngan** [comment]
My bad, I forgot up update my local repo...
